### ISSUE TITLE
请问怎么修改为定时打新和定时交易（指定时间指定价格指定数量交易）

### ISSUE THREAD

**Issue by cnken** [MrZilinXiao/Auto-Make-Money#1]
在您这个基础上，请问怎么修改为定时打新和定时交易（指定时间指定价格指定数量交易）

**Comment by MrZilinXiao** [comment]
这个功能可以结合apscheduler完成，具体参考https://github.com/MrZilinXiao/Auto-Make-Money/blob/1894cb28bb6b0ca9094aa2b16f8a390af1604419/main.py#L33 ，此处实现了每日定时打新；

**Comment by MrZilinXiao** [comment]
The issue closed since no further questions. Reopen it if necessary.
