### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by ZhangLanDan** [MrZilinXiao/Auto-Make-Money#2]
from pywinauto.win32functions import SetForegroundWindow, ShowWindow
ImportError: cannot import name 'SetForegroundWindow' from 'pywinauto.win32functions'

**Comment by MrZilinXiao** [comment]
请注明报错位置，谢谢

**Comment by ZhangLanDan** [comment]
好的，大善人！







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MrZilinXiao/Auto-Make-Money"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月3日(星期二) 下午3:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MrZilinXiao/Auto-Make-Money] 运行不了 (#2)





 
请注明报错位置，谢谢
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MrZilinXiao** [comment]
无后续回复，先关闭您的issue，若有其他需求欢迎随时打开。
