### ISSUE TITLE
大佬，有没有可能通过同花顺Linux版本实现Linux虚拟机的自动打新

### ISSUE THREAD

**Issue by Grefer** [MrZilinXiao/Auto-Make-Money#3]
目前手头没有windows版本的虚拟机，倒是有个BWG的小机场，刚好看到同花顺也有Linux版本，所以问下大佬，有没有这种可能实现

**Comment by MrZilinXiao** [comment]
此脚本目前依赖pywin32，或许你可以跟easytrade的作者反馈一下☺️
