### ISSUE TITLE
BlockingScheduler day_of_week

### ISSUE THREAD

**Issue by icaca** [MrZilinXiao/Auto-Make-Money#7]
scheduler.add_job(job, 'cron', day_of_week='1-5', hour=9, minute=35)

day_of_week (int|str) – number or name of weekday (0-6 or mon,tue,wed,thu,fri,sat,sun) 

是不是应该改成0-4？

**Comment by MrZilinXiao** [comment]
抱歉迟复！的确哈，马上修改。
另：其实每天执行也没关系的，毕竟scheduler好像也没办法知道内地证券市场的调休，每天执行只会每天定时多一个提醒罢了。
